# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-13 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, default='code.jpg', upload_to=b''),
        ),
    ]
